version: "2.3" #Use this version strictly
services:
  redis-dredd:
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    container_name: redis-dredd
    restart: always
    ports:
      - "6379:6379"
    networks:
      - dredd-network

  rabbitmq-dredd:
    image: rabbitmq
    container_name: rabbitmq-dredd
    restart: always
    ports:
      - "5672:5672"
    networks:
      - dredd-network

networks:
  dredd-network:
    external:
      name: dredd-network
      
  # server:
  #   build: ./server
  #   restart: always
  #   ports:
  #     - "3002:3002"

  # worker:
  #   build: ./worker
  #   restart: always
  # pids_limit: 60 # Max number of processes running in thw container.
  # cpus: 1 # No of CPUs allocated
  # mem_limit: 150M # Hard limit
