version: '2.3'

services:
  node-worker-1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3005:3005
    networks:
      - dredd-network

networks:
  dredd-network:
    external:
      name: dredd-network
