version: '2.3'

services:
  node-worker:
    build:
      context: .
      dockerfile: Dockerfile

    networks:
      - dredd-network
    environment:
      - QUEUE_NAME=${QUEUE_NAME}

networks:
  dredd-network:
    external:
      name: dredd-network
