version: '2.3'

services:
  node-worker-2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3006:3006
    networks:
      - dredd-network

networks:
  dredd-network:
    external:
      name: dredd-network
